#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#------------------------------- nanoFluid4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# cleancase is function that removes the files and directories.(rm -f : remove the file, rm -r : remove the directory).
cleancase ()
{
    rm -r Gnu*
    rm -r processor*
rm -f constant/polyMesh/boundary*
rm -f constant/polyMesh/meshMetaDict
rm -f fluidDomain.fms
rm -f postProcess.txt
}

# (getApplication) is an command to find the solver name from the controlDict file. Also, ($) use for the variable.
application=$(getApplication)

cleancase
./Allclean

echo meshing...
surfaceFeatureEdges fluidDomain.stl fluidDomain.fms
cartesianMesh
autoPatch 80 -overwrite
createPatch -overwrite
transformPoints -scale '(0.001 0.001 0.001)'
checkMesh

echo run solver ...
buoyantBoussinesqPisoFoam
#application

# -------------------------------------------------------------------------- end-of-file






